#pragma once

#include <cstddef>
#include <cstdint>

// The gzipped airport typeahead payload, embedded via
// `board_build.embed_files = data/airport_index.json.gz` in platformio.ini.
// Regenerated by `python3 scripts/build_web_data.py`.
extern const uint8_t _binary_data_airport_index_json_gz_start[] asm(
    "_binary_data_airport_index_json_gz_start");
extern const uint8_t _binary_data_airport_index_json_gz_end[] asm(
    "_binary_data_airport_index_json_gz_end");

namespace plane_radar::portal {

// HTML/JS injected into every WiFiManager page via setCustomHeadElement().
//
// On EVERY page: kills iOS's initial auto-capitalization on password fields.
// On the LAN /param page: adds a "Search address or airport" box above each
//   coord pair; replaces the focus-airports raw-JSON field with a chip editor;
//   auto-populates home coords via a public IP-geolocation call on first load
//   when they're still 0/blank.
// On the captive-portal /param page (which we deliberately don't attach any
//   params to), this is a no-op past the caps fix.
constexpr char kCustomHead[] = R"HTML(<script>
(function(){
"use strict";
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c];});}
function deb(fn,ms){var t;return function(){var a=arguments,c=this;clearTimeout(t);t=setTimeout(function(){fn.apply(c,a);},ms);};}
function fixCaps(){
  document.querySelectorAll("input[type=password], input[name=s]").forEach(function(el){
    el.setAttribute("autocapitalize","off");
    el.setAttribute("autocorrect","off");
    el.setAttribute("spellcheck","false");
  });
}
var apIdxP=null;
function apIdx(){
  if(apIdxP) return apIdxP;
  apIdxP=fetch("/data/airport_index.json").then(function(r){return r.ok?r.json():[];}).catch(function(){return[];});
  return apIdxP;
}
// Row shape from the device-served /data/airport_index.json (trimmed):
//   [icao, iata, city, lat, lon]
function apSearch(idx,q){
  q=q.toLowerCase();var out=[];
  for(var i=0;i<idx.length&&out.length<8;i++){
    var r=idx[i],ic=(r[0]||"").toLowerCase(),ia=(r[1]||"").toLowerCase(),ci=(r[2]||"").toLowerCase();
    var hit=ic===q||ia===q||ic.indexOf(q)===0||ia.indexOf(q)===0||ci.indexOf(q)===0||ci.indexOf(q)>=0;
    if(hit) out.push({label:(r[1]?r[1]+" · ":"")+r[0]+" — "+r[2],lat:r[3],lon:r[4],name:r[1]||r[0]});
  }
  return out;
}
function addrSearch(q,sig){
  return fetch("https://radar.benyaffe.com/api/geocode?q="+encodeURIComponent(q),{signal:sig})
    .then(function(r){return r.ok?r.json():[];})
    .then(function(rows){return rows.slice(0,5).map(function(x){return{label:"📍 "+x.display_name,lat:x.lat,lon:x.lon,name:x.display_name.split(",")[0]};});})
    .catch(function(){return[];});
}
function search(q){
  if(q.length<2) return Promise.resolve([]);
  var ac=new AbortController();
  return Promise.all([
    apIdx().then(function(i){return apSearch(i,q);}),
    q.length>=3?addrSearch(q,ac.signal):Promise.resolve([])
  ]).then(function(rs){return rs[0].concat(rs[1]);});
}
function makeSearchBox(ph){
  var box=document.createElement("div");
  box.style.margin="4px 0";
  box.innerHTML=
    '<input type="text" placeholder="'+ph+'" style="width:100%;padding:5px;font-size:1em" autocapitalize="off" autocorrect="off" spellcheck="false">'+
    '<div class="pr-hits" style="display:none;border:1px solid #ccc;max-height:180px;overflow:auto;font-size:.9em;background:#fff"></div>';
  return box;
}
function renderHits(hits,results,pick){
  if(!results.length){hits.style.display="none";hits.innerHTML="";return;}
  hits.innerHTML=results.map(function(r,i){return '<div class="pr-hit" data-i="'+i+'" style="padding:6px;cursor:pointer;border-bottom:1px solid #eee">'+esc(r.label)+'</div>';}).join("");
  hits.style.display="block";
  hits.querySelectorAll(".pr-hit").forEach(function(el){
    el.addEventListener("click",function(){pick(results[+el.getAttribute("data-i")]);});
  });
}
function attachCoordSearch(latEl,lonEl){
  var box=makeSearchBox("Search address or airport (e.g. SFO, 2125 Bryant St)");
  var anchor=latEl.previousElementSibling;
  var host=(anchor&&anchor.tagName==="LABEL")?anchor:latEl;
  host.parentNode.insertBefore(box,host);
  var input=box.querySelector("input"),hits=box.querySelector(".pr-hits");
  var run=deb(function(){
    search(input.value.trim()).then(function(rs){
      renderHits(hits,rs,function(r){
        latEl.value=Number(r.lat).toFixed(6);
        lonEl.value=Number(r.lon).toFixed(6);
        input.value=r.name;
        hits.style.display="none";
        latEl.dispatchEvent(new Event("input"));
        lonEl.dispatchEvent(new Event("input"));
      });
    });
  },300);
  input.addEventListener("input",run);
  document.addEventListener("click",function(e){if(!box.contains(e.target)) hits.style.display="none";});
}
function attachFocusEditor(field){
  var wrap=document.createElement("div");
  wrap.style.margin="4px 0";
  wrap.innerHTML=
    '<div class="pr-chips" style="display:flex;flex-wrap:wrap;gap:4px;margin-bottom:4px"></div>'+
    '<input type="text" placeholder="Add airport or address (e.g. PAO)" style="width:100%;padding:5px;font-size:1em" autocapitalize="off" autocorrect="off" spellcheck="false">'+
    '<div class="pr-hits" style="display:none;border:1px solid #ccc;max-height:180px;overflow:auto;font-size:.9em;background:#fff"></div>';
  field.parentNode.insertBefore(wrap,field);
  field.style.display="none";
  var lbl=field.previousElementSibling;
  if(lbl&&lbl.tagName==="LABEL") lbl.style.display="none";
  var chips=wrap.querySelector(".pr-chips"),input=wrap.querySelector("input"),hits=wrap.querySelector(".pr-hits");
  var rng=[5,10,15,25];
  var arr=[];
  try{arr=JSON.parse(field.value||"[]");if(!Array.isArray(arr))arr=[];}catch(e){arr=[];}
  function ser(){field.value=JSON.stringify(arr.map(function(e){return{name:e.name,lat:e.lat,lon:e.lon,range_idx:e.range_idx};}));}
  function draw(){
    chips.innerHTML=arr.map(function(e,i){
      var opts=rng.map(function(nm,ri){return '<option value="'+ri+'"'+(ri===e.range_idx?" selected":"")+">"+nm+"nm</option>";}).join("");
      return '<span data-i="'+i+'" style="border:1px solid #ccc;padding:4px 6px;border-radius:3px;display:inline-flex;align-items:center;gap:4px;background:#f8f8f8"><b>'+esc(e.name)+'</b><select class="pr-r">'+opts+'</select><button type="button" class="pr-x" style="padding:2px 6px;background:#dc3630;color:#fff;border:0;border-radius:3px;cursor:pointer">×</button></span>';
    }).join("");
    chips.querySelectorAll(".pr-x").forEach(function(b){b.addEventListener("click",function(){arr.splice(+b.parentNode.getAttribute("data-i"),1);draw();ser();});});
    chips.querySelectorAll(".pr-r").forEach(function(s){s.addEventListener("change",function(){arr[+s.parentNode.getAttribute("data-i")].range_idx=+s.value;ser();});});
  }
  draw();ser();
  var run=deb(function(){
    search(input.value.trim()).then(function(rs){
      renderHits(hits,rs,function(r){
        arr.push({name:String(r.name).slice(0,16),lat:+Number(r.lat).toFixed(6),lon:+Number(r.lon).toFixed(6),range_idx:1});
        input.value="";hits.style.display="none";draw();ser();
      });
    });
  },300);
  input.addEventListener("input",run);
  document.addEventListener("click",function(e){if(!wrap.contains(e.target)) hits.style.display="none";});
}
function autoLocate(latEl,lonEl){
  if(!latEl||!lonEl) return;
  var la=parseFloat(latEl.value),lo=parseFloat(lonEl.value);
  if(!isNaN(la)&&!isNaN(lo)&&!(la===0&&lo===0)) return;
  fetch("https://ipapi.co/json/").then(function(r){return r.ok?r.json():null;}).then(function(d){
    if(!d||typeof d.latitude!=="number"||typeof d.longitude!=="number") return;
    latEl.value=d.latitude.toFixed(6);lonEl.value=d.longitude.toFixed(6);
  }).catch(function(){});
}
function init(){
  fixCaps();
  var lh=document.querySelector("input[name=radar_lat]");
  var oh=document.querySelector("input[name=radar_lon]");
  var lm=document.querySelector("input[name=metar_lat]");
  var om=document.querySelector("input[name=metar_lon]");
  var fr=document.querySelector("textarea[name=focus_ring],input[name=focus_ring]");
  if(lh&&oh) attachCoordSearch(lh,oh);
  if(lm&&om) attachCoordSearch(lm,om);
  if(fr) attachFocusEditor(fr);
  if(lh&&oh) autoLocate(lh,oh);
}
if(document.readyState==="loading") document.addEventListener("DOMContentLoaded",init); else init();
})();
</script>)HTML";

}  // namespace plane_radar::portal
