// Generated by scripts/build_fallback_tile.py — do not edit.
//
// World-overview tile (z=0, x=0, y=0) baked into firmware flash so
// the device can render *something* on cold boot with no cached
// tiles. Very coarse coastlines + top ~1000 airports worldwide,
// no runway detail. Size: 14472 bytes.
//
// Regenerate when the tile format or the base data changes:
//     scripts/build_fallback_tile.py

#pragma once

#include <cstddef>
#include <cstdint>

namespace data::tile {

extern const uint8_t kFallbackTile[];
constexpr size_t kFallbackTileSize = 14472;

}  // namespace data::tile
