// Verifies the flash-embedded fallback tile is a valid tile the
// firmware TileReader can parse. If the fallback bytes are ever
// truncated / corrupted / regenerated with an incompatible format
// change, this test fails and the device would boot to a blank
// screen — better to catch it in CI.
//
// The fallback bytes themselves live in src/data/fallback_tile.cpp,
// generated by scripts/build_fallback_tile.py. tests/test_fallback_
// tile.py enforces size + content on the Python side.
//
// Run via `pio test -e native_test`.

#include <cstdint>
#include <unity.h>

#include "data/fallback_tile.h"
#include "data/tile_reader.h"

#define NATIVE_STUBS_DEFINE
#include "../common/native_stubs.h"

void setUp(void) {}
void tearDown(void) {}

void test_fallback_bytes_parse(void) {
  data::tile::TileReader r;
  TEST_ASSERT_TRUE(r.init(data::tile::kFallbackTile,
                           data::tile::kFallbackTileSize));
  TEST_ASSERT_EQUAL_UINT8(0, r.z());
  TEST_ASSERT_EQUAL_UINT16(0, r.x());
  TEST_ASSERT_EQUAL_UINT16(0, r.y());
}

void test_fallback_has_land_section(void) {
  data::tile::TileReader r;
  r.init(data::tile::kFallbackTile, data::tile::kFallbackTileSize);
  uint32_t len = 0;
  const uint8_t* p = r.sectionBegin(data::tile::Section::Land, &len);
  TEST_ASSERT_NOT_NULL(p);
  TEST_ASSERT_TRUE(len > 0);

  const uint8_t* end = p + len;
  uint16_t poly_count = 0;
  TEST_ASSERT_TRUE(
      data::tile::TileReader::readSectionCount(&p, end, &poly_count));
  // See tests/test_fallback_tile.py::test_fallback_tile_has_land_and_airports.
  TEST_ASSERT_TRUE(poly_count > 20);
}

void test_fallback_has_airport_section(void) {
  data::tile::TileReader r;
  r.init(data::tile::kFallbackTile, data::tile::kFallbackTileSize);
  uint32_t len = 0;
  const uint8_t* p = r.sectionBegin(data::tile::Section::Airports, &len);
  TEST_ASSERT_NOT_NULL(p);
  TEST_ASSERT_TRUE(len > 0);

  const uint8_t* end = p + len;
  uint16_t apt_count = 0;
  TEST_ASSERT_TRUE(
      data::tile::TileReader::readSectionCount(&p, end, &apt_count));
  TEST_ASSERT_TRUE(apt_count >= 100);

  // Sanity: parse the first airport and check its ident is non-empty
  // ASCII — catches corruption where the byte array got misaligned
  // via a bad edit.
  data::tile::AirportView a;
  TEST_ASSERT_TRUE(data::tile::TileReader::readAirport(&p, end, &a));
  TEST_ASSERT_TRUE(a.ident[0] != '\0');
  TEST_ASSERT_TRUE(a.ident[0] >= 'A' && a.ident[0] <= 'Z');
}

int main(int /*argc*/, char** /*argv*/) {
  UNITY_BEGIN();
  RUN_TEST(test_fallback_bytes_parse);
  RUN_TEST(test_fallback_has_land_section);
  RUN_TEST(test_fallback_has_airport_section);
  return UNITY_END();
}
