#!/usr/bin/env python3
"""Bake the tiny world-overview tile that ships in firmware flash.

Purpose: on first boot with no cached tiles, the device still shows
*something* — a continent outline and the world's biggest airports —
rather than a blank screen. The plan requires this for offline boot.

Design constraints:
  * Whole world in a single z=0 tile (not part of the normal pyramid,
    which starts at z=3). Reader-side this looks like any other tile.
  * Coarse Natural Earth 50m sources, aggressive DP simplification —
    the resulting file must fit in flash without stealing bytes from
    firmware. Target: < 20 KB.
  * Only large + medium airports worldwide (no small GA fields), no
    runway detail (saves ~16 bytes per airport).
  * Emits both a raw .bin (for the on-host round-trip test) and a
    C++ header/source pair (constexpr uint8_t kFallbackTile[]) that
    firmware includes.

Usage:
  scripts/build_fallback_tile.py

Regen cadence: whenever build_tiles.py updates or Natural Earth /
OurAirports moves. Not on the monthly CI schedule — this is a
manually-refreshed asset since it's baked into firmware, not the
website.
"""
from __future__ import annotations

import csv
import json
import sys
import textwrap
import urllib.request
from pathlib import Path

import tile_airports as ta
import tile_coastline as tc
import tile_format as tf
import tile_polygons as tp

ROOT = Path(__file__).resolve().parents[1]
CACHE_DIR = ROOT / ".local-data"
OUT_BIN = CACHE_DIR / "fallback_tile.bin"
OUT_HEADER = ROOT / "include" / "data" / "fallback_tile.h"
OUT_SOURCE = ROOT / "src" / "data" / "fallback_tile.cpp"

NE = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson"
SOURCES = {
    "coastline": f"{NE}/ne_50m_coastline.geojson",
    "land": f"{NE}/ne_50m_land.geojson",
}
OA = "https://raw.githubusercontent.com/davidmegginson/ourairports-data/main"
AIRPORTS_URL = f"{OA}/airports.csv"

# Coarser than any pyramid zoom — this is the WORLD in a single tile.
# ~1.0° ≈ 111 km at the equator: enough for continent shapes only,
# no coastline detail. That's the point — the fallback is "the world
# exists" not "here's your local airport." Locally-fetched tiles at
# 0.002° take over as soon as the device has a location.
FALLBACK_TOL_DEG = 1.0

# Cap how many airports get baked into flash. Sorted by tier then by
# ICAO so the top international hubs win; small enough that the
# combined tile is <30 KB.
FALLBACK_MAX_AIRPORTS = 150


def download(url: str, dest: Path) -> Path:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    if not dest.exists():
        print(f"downloading {url}", file=sys.stderr)
        urllib.request.urlretrieve(url, dest)
    return dest


def load_geojson_features(url: str) -> list[dict]:
    dest = CACHE_DIR / Path(url).name
    download(url, dest)
    return json.loads(dest.read_text()).get("features", [])


def fetch_csv_rows(url: str) -> list[dict]:
    dest = CACHE_DIR / Path(url).name
    download(url, dest)
    with dest.open(newline="") as f:
        return list(csv.DictReader(f))


def build_fallback_tile() -> tf.Tile:
    land_features = load_geojson_features(SOURCES["land"])
    airport_rows = fetch_csv_rows(AIRPORTS_URL)

    # Land polygon outlines carry the continent-shape information a
    # world overview needs. We skip coastlines entirely for the
    # fallback — they'd duplicate the land outer edges, and Natural
    # Earth 50m still has ~1400 individual coastline polylines
    # worldwide even at 1° simplification, which blows the flash
    # budget without adding anything a user can see at this zoom.
    land_polygons: list[tf.Polyline] = []
    for ring in tp._extract_polygon_rings(land_features):
        for poly in tp.distribute_polygon_to_tiles(ring, z=0, tol_deg=FALLBACK_TOL_DEG).values():
            land_polygons.append(poly)

    # Trim runways from every airport to keep the flash payload tiny —
    # the fallback tile is for "you can see the world exists," not
    # "you can plan an approach." Only the top ~150 large airports.
    airports_all = ta.build_airports(airport_rows, runways=[], iap_icaos=[])
    airports = [tf.Airport(a.ident, a.lat, a.lon, a.tier, a.instrument_approach, [])
                for a in airports_all if a.tier >= 3][:FALLBACK_MAX_AIRPORTS]

    return tf.Tile(
        z=0, x=0, y=0,
        coast=[],
        land=land_polygons,
        water=[],
        airports=airports,
    )


def emit_cpp(data: bytes) -> None:
    OUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    OUT_HEADER.write_text(textwrap.dedent(f"""\
        // Generated by scripts/build_fallback_tile.py — do not edit.
        //
        // World-overview tile (z=0, x=0, y=0) baked into firmware flash so
        // the device can render *something* on cold boot with no cached
        // tiles. Very coarse coastlines + top ~1000 airports worldwide,
        // no runway detail. Size: {len(data)} bytes.
        //
        // Regenerate when the tile format or the base data changes:
        //     scripts/build_fallback_tile.py

        #pragma once

        #include <cstddef>
        #include <cstdint>

        namespace data::tile {{

        extern const uint8_t kFallbackTile[];
        constexpr size_t kFallbackTileSize = {len(data)};

        }}  // namespace data::tile
    """))

    # Emit the byte array in rows of 16 for readable diffs.
    OUT_SOURCE.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    lines.append("// Generated by scripts/build_fallback_tile.py — do not edit.")
    lines.append("")
    lines.append('#include "data/fallback_tile.h"')
    lines.append("")
    lines.append("namespace data::tile {")
    lines.append("")
    lines.append("const uint8_t kFallbackTile[] = {")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        row = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {row},")
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace data::tile")
    OUT_SOURCE.write_text("\n".join(lines) + "\n")


def main() -> None:
    tile = build_fallback_tile()
    data = tf.encode(tile)
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    OUT_BIN.write_bytes(data)
    emit_cpp(data)
    print(f"wrote {OUT_BIN.relative_to(ROOT)} ({len(data)} bytes)", file=sys.stderr)
    print(f"wrote {OUT_HEADER.relative_to(ROOT)}", file=sys.stderr)
    print(f"wrote {OUT_SOURCE.relative_to(ROOT)}", file=sys.stderr)
    print(f"  {len(tile.coast)} coast polylines, "
          f"{len(tile.land)} land polygons, "
          f"{len(tile.airports)} airports",
          file=sys.stderr)


if __name__ == "__main__":
    main()
