// Tests for data::tile::TileReader — parses the binary format produced by
// scripts/tile_format.py.
//
// The fixture bytes below were generated by running the exact recipe
// documented in tests/test_tile_reader_fixture.py — a pytest guardrail
// re-generates them on every pytest run and fails loudly if this array
// has drifted from what tile_format.encode() would produce today. If
// you get a failure there, run that pytest with -v to see the fresh
// bytes and paste them in below.
//
// Run via `pio test -e native_test`.

#include <cstdint>
#include <cstring>
#include <unity.h>

#include "data/tile_reader.h"

// The native_test env pulls in ui/map_projection.cpp for every test
// binary; provide the stub symbols it references from a single place.
#define NATIVE_STUBS_DEFINE
#include "../common/native_stubs.h"

// tile_format.encode(Tile(z=7, x=20, y=37,
//   coast=[Polyline([(-122.5, 37.75), (-122.4, 37.80), (-122.3, 37.85)])],
//   airports=[
//     Airport('KSFO', 37.6188, -122.375, tier=3, iap=True,
//             runways=[Runway(37.61, -122.38, 37.62, -122.37)]),
//     Airport('KOAK', 37.7201, -122.2212, tier=3, iap=True, runways=[]),
//   ]))
static constexpr uint8_t kFixture[] = {
  0x50, 0x52, 0x54, 0x31, 0x01, 0x07, 0x14, 0x00, 0x25, 0x00, 0x02, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x24, 0x00, 0x00, 0x00, 0x2c, 0x00, 0x00, 0x00,
  0x03, 0x00, 0x00, 0x00, 0x50, 0x00, 0x00, 0x00, 0x36, 0x00, 0x00, 0x00,
  0x01, 0x00, 0x03, 0x00, 0x60, 0x31, 0x80, 0x16, 0xc0, 0xfb, 0xfb, 0xb6,
  0xa0, 0x73, 0x8f, 0x16, 0x40, 0x80, 0x1a, 0xb7, 0x60, 0x31, 0x80, 0x16,
  0xc0, 0xfb, 0xfb, 0xb6, 0x80, 0xd2, 0x87, 0x16, 0x00, 0x3e, 0x0b, 0xb7,
  0xa0, 0x73, 0x8f, 0x16, 0x40, 0x80, 0x1a, 0xb7, 0x02, 0x00, 0x60, 0x2c,
  0x6c, 0x16, 0x90, 0x0e, 0x0f, 0xb7, 0x0f, 0x4b, 0x53, 0x46, 0x4f, 0x00,
  0x00, 0x00, 0x00, 0x01, 0xa0, 0xd4, 0x6a, 0x16, 0x40, 0x4b, 0x0e, 0xb7,
  0x40, 0x5b, 0x6c, 0x16, 0xe0, 0xd1, 0x0f, 0xb7, 0x68, 0xa1, 0x7b, 0x16,
  0x60, 0x86, 0x26, 0xb7, 0x07, 0x4b, 0x4f, 0x41, 0x4b, 0x00, 0x00, 0x00,
  0x00, 0x00,
};

// Reference values matching the Python encoder (deg → e7 rounded).
static constexpr int32_t kSfoLatE7 = 376188000;
static constexpr int32_t kSfoLonE7 = -1223750000;
static constexpr int32_t kOakLatE7 = 377201000;
static constexpr int32_t kOakLonE7 = -1222212000;

void setUp(void) {}
void tearDown(void) {}

void test_init_rejects_null(void) {
  data::tile::TileReader r;
  TEST_ASSERT_FALSE(r.init(nullptr, 0));
  TEST_ASSERT_FALSE(r.init(kFixture, 0));
}

void test_init_rejects_short_header(void) {
  data::tile::TileReader r;
  TEST_ASSERT_FALSE(r.init(kFixture, 8));
}

void test_init_rejects_bad_magic(void) {
  uint8_t bad[sizeof(kFixture)];
  std::memcpy(bad, kFixture, sizeof(kFixture));
  bad[0] = 'X';
  data::tile::TileReader r;
  TEST_ASSERT_FALSE(r.init(bad, sizeof(bad)));
}

void test_init_rejects_wrong_version(void) {
  uint8_t bad[sizeof(kFixture)];
  std::memcpy(bad, kFixture, sizeof(kFixture));
  bad[4] = 99;  // version byte
  data::tile::TileReader r;
  TEST_ASSERT_FALSE(r.init(bad, sizeof(bad)));
}

void test_init_accepts_fixture(void) {
  data::tile::TileReader r;
  TEST_ASSERT_TRUE(r.init(kFixture, sizeof(kFixture)));
  TEST_ASSERT_EQUAL_UINT8(7, r.z());
  TEST_ASSERT_EQUAL_UINT16(20, r.x());
  TEST_ASSERT_EQUAL_UINT16(37, r.y());
  TEST_ASSERT_EQUAL_UINT8(2, r.sectionCount());
}

void test_section_begin_returns_null_for_missing_section(void) {
  data::tile::TileReader r;
  r.init(kFixture, sizeof(kFixture));
  uint32_t len = 999;
  const uint8_t* p = r.sectionBegin(data::tile::Section::Water, &len);
  TEST_ASSERT_NULL(p);
  TEST_ASSERT_EQUAL_UINT32(0, len);
}

void test_section_begin_returns_coast_section(void) {
  data::tile::TileReader r;
  r.init(kFixture, sizeof(kFixture));
  uint32_t len = 0;
  const uint8_t* p = r.sectionBegin(data::tile::Section::Coast, &len);
  TEST_ASSERT_NOT_NULL(p);
  TEST_ASSERT_TRUE(len > 0);
}

void test_read_coast_polyline_matches_reference(void) {
  data::tile::TileReader r;
  r.init(kFixture, sizeof(kFixture));
  uint32_t len = 0;
  const uint8_t* p = r.sectionBegin(data::tile::Section::Coast, &len);
  const uint8_t* end = p + len;
  uint16_t poly_count = 0;
  TEST_ASSERT_TRUE(data::tile::TileReader::readSectionCount(&p, end, &poly_count));
  TEST_ASSERT_EQUAL_UINT16(1, poly_count);
  data::tile::PolylineView view;
  TEST_ASSERT_TRUE(data::tile::TileReader::readPolyline(&p, end, &view));
  TEST_ASSERT_EQUAL_UINT16(3, view.point_count);
  int32_t lat = 0, lon = 0;
  view.getPoint(0, &lat, &lon);
  TEST_ASSERT_EQUAL_INT32(377500000, lat);   // 37.75
  TEST_ASSERT_EQUAL_INT32(-1225000000, lon); // -122.5
  view.getPoint(2, &lat, &lon);
  TEST_ASSERT_EQUAL_INT32(378500000, lat);   // 37.85
  TEST_ASSERT_EQUAL_INT32(-1223000000, lon); // -122.3
}

void test_read_airports_matches_reference(void) {
  data::tile::TileReader r;
  r.init(kFixture, sizeof(kFixture));
  uint32_t len = 0;
  const uint8_t* p = r.sectionBegin(data::tile::Section::Airports, &len);
  const uint8_t* end = p + len;
  uint16_t apt_count = 0;
  TEST_ASSERT_TRUE(data::tile::TileReader::readSectionCount(&p, end, &apt_count));
  TEST_ASSERT_EQUAL_UINT16(2, apt_count);

  data::tile::AirportView a;
  TEST_ASSERT_TRUE(data::tile::TileReader::readAirport(&p, end, &a));
  TEST_ASSERT_EQUAL_STRING("KSFO", a.ident);
  TEST_ASSERT_EQUAL_INT32(kSfoLatE7, a.lat_e7);
  TEST_ASSERT_EQUAL_INT32(kSfoLonE7, a.lon_e7);
  TEST_ASSERT_EQUAL_UINT8(3, a.tier());
  TEST_ASSERT_TRUE(a.instrumentApproach());
  TEST_ASSERT_EQUAL_UINT8(1, a.runway_count);
  int32_t la1, lo1, la2, lo2;
  a.getRunway(0, &la1, &lo1, &la2, &lo2);
  TEST_ASSERT_EQUAL_INT32(376100000, la1);
  TEST_ASSERT_EQUAL_INT32(-1223800000, lo1);
  TEST_ASSERT_EQUAL_INT32(376200000, la2);
  TEST_ASSERT_EQUAL_INT32(-1223700000, lo2);

  TEST_ASSERT_TRUE(data::tile::TileReader::readAirport(&p, end, &a));
  TEST_ASSERT_EQUAL_STRING("KOAK", a.ident);
  TEST_ASSERT_EQUAL_INT32(kOakLatE7, a.lat_e7);
  TEST_ASSERT_EQUAL_INT32(kOakLonE7, a.lon_e7);
  TEST_ASSERT_EQUAL_UINT8(0, a.runway_count);
  TEST_ASSERT_TRUE(a.instrumentApproach());
}

void test_read_polyline_rejects_truncated_input(void) {
  const uint8_t buf[3] = {0, 0, 0};  // less than the 18-byte prefix
  const uint8_t* p = buf;
  data::tile::PolylineView view;
  TEST_ASSERT_FALSE(data::tile::TileReader::readPolyline(&p, buf + sizeof(buf), &view));
}

void test_read_airport_rejects_truncated_input(void) {
  const uint8_t buf[10] = {};  // less than the 18-byte prefix
  const uint8_t* p = buf;
  data::tile::AirportView view;
  TEST_ASSERT_FALSE(data::tile::TileReader::readAirport(&p, buf + sizeof(buf), &view));
}

void test_init_rejects_section_offset_past_end(void) {
  // Take a valid fixture, corrupt the first section index entry's
  // offset so it points off the end of the buffer.
  uint8_t bad[sizeof(kFixture)];
  std::memcpy(bad, kFixture, sizeof(kFixture));
  // First index entry starts at offset 12 (after header). Offset field
  // is at entry+4. Bump it to a huge value.
  const uint32_t huge = 0xFFFFFFFEu;
  std::memcpy(bad + 12 + 4, &huge, 4);
  data::tile::TileReader r;
  TEST_ASSERT_FALSE(r.init(bad, sizeof(bad)));
}

int main(int /*argc*/, char** /*argv*/) {
  UNITY_BEGIN();
  RUN_TEST(test_init_rejects_null);
  RUN_TEST(test_init_rejects_short_header);
  RUN_TEST(test_init_rejects_bad_magic);
  RUN_TEST(test_init_rejects_wrong_version);
  RUN_TEST(test_init_accepts_fixture);
  RUN_TEST(test_section_begin_returns_null_for_missing_section);
  RUN_TEST(test_section_begin_returns_coast_section);
  RUN_TEST(test_read_coast_polyline_matches_reference);
  RUN_TEST(test_read_airports_matches_reference);
  RUN_TEST(test_read_polyline_rejects_truncated_input);
  RUN_TEST(test_read_airport_rejects_truncated_input);
  RUN_TEST(test_init_rejects_section_offset_past_end);
  return UNITY_END();
}
