// Generated by scripts/build_focus_airports.py — do not edit.
#include "data/focus_airports.h"

namespace data::focus_airports {

const Airport kAirports[] = {
  {"KHAF", 375134010, -1225009995},
  {"KHWD", 376591988, -1221220016},
  {"KPAO", 374611020, -1221149980},
  {"KSQL", 375131300, -1222508380},
};

const Runway kRunways[] = {
  {0, 375185013, -1225070038, 375084000, -1224950027, 1524},
  {1, 376619987, -1221299973, 376543007, -1221129990, 1736},
  {1, 376624985, -1221269989, 376581993, -1221179962, 947},
  {2, 374637985, -1221179962, 374584999, -1221119995, 744},
  {3, 375144997, -1222529984, 375092010, -1222470016, 799},
};

}  // namespace data::focus_airports
